name: Build All

on:
  push:
    branches:
      - "stable"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            { os: roborio, port: armel },
            { os: bionic, port: armhf },
            { os: bionic, port: arm64 },
            { os: focal, port: armhf },
            { os: focal, port: arm64 },
            { os: buster, port: armhf },
            { os: buster, port: arm64 },
            { os: bullseye, port: armhf },
            { os: bullseye, port: arm64 },
          ]
        host:
          [
            {
              os-cfg: linux_x86_64,
              runner: ubuntu-latest,
              docker: true,
              docker-img: 14.04,
            },
            {
              os-cfg: windows_i686,
              runner: ubuntu-latest,
              docker: true,
              docker-img: 20.04,
            },
            {
              os-cfg: windows_x86_64,
              runner: ubuntu-latest,
              docker: true,
              docker-img: 20.04,
            },
            {
              os-cfg: macos_x86_64,
              runner: macos-latest,
              docker: false,
              docker-img: "",
            },
            {
              os-cfg: sysroot,
              runner: ubuntu-latest,
              docker: true,
              docker-img: alpine,
            },
          ]
    name: Build ${{ matrix.target.os }}-${{ matrix.target.port }} for ${{ matrix.host.os-cfg }}
    runs-on: ${{ matrix.host.runner }}
    steps:
      - uses: actions/checkout@v2
      - name: Prep MacOS
        if: startsWith(matrix.host.runner, 'macos')
        run: brew install coreutils binutils gnu-tar gzip
      - name: Import Developer ID Certificate
        uses: wpilibsuite/import-signing-certificate@v1
        with:
          certificate-data: ${{ secrets.APPLE_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          keychain-password: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        if: github.repository_owner == 'wpilibsuite' && startsWith(matrix.host.runner, 'macos')
      - name: Build on docker
        if: ${{ matrix.host.docker }}
        run: ./build-docker.sh ${{matrix.host.docker-img}} hosts/${{matrix.host.os-cfg}}.env targets/${{matrix.target.os}} ${{matrix.target.port}}
      - name: Build on native
        if: startsWith(matrix.host.runner, 'macos')
        run: ./build.sh hosts/${{matrix.host.os-cfg}}.env targets/${{matrix.target.os}} ${{matrix.target.port}}
        env:
          APPLE_DEVELOPER_ID: ${{ secrets.APPLE_DEVELOPER_ID }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.target.os}}-${{matrix.target.port}}-${{matrix.host.os-cfg}}
          path: build/${{matrix.target.os}}-${{matrix.target.port}}/*/${{matrix.target.port}}-${{matrix.target.os}}-*-*-Toolchain-*.*
  test-sysroot:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target:
          [
            { os: roborio, port: armel },
            { os: roborio-testing, port: armel },
            { os: bionic, port: armhf },
            { os: bionic, port: arm64 },
            { os: focal, port: armhf },
            { os: focal, port: arm64 },
            { os: buster, port: armhf },
            { os: buster, port: arm64 },
            { os: bullseye, port: armhf },
            { os: bullseye, port: arm64 },
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{matrix.target.os}}-${{matrix.target.port}}-linux_x86_64
      - name: Fix directory
        run: mv Linux/* .
      - name: Print directory for logging
        run: ls -lah
      - name: Run test
        run: ./test.sh hosts/linux_x86_64.env targets/${{matrix.target.os}} ${{matrix.target.port}}
